declare module 'react-native-ico-sign-and-symbols' {
    import { ReactNode } from 'react';

    type iconNames = '11-photo-s' |
      '11-weather-s' |
      '14-weather-s' |
      '15-s-for-menu' |
      '16-weather-illustrations' |
      '1st-place-37' |
      '1st-place-43' |
      '1st-place' |
      '20-s-for-menu' |
      '21-weather-s' |
      '2nd-place-44' |
      '2nd-place' |
      '3rd-place-11' |
      '3rd-place-18' |
      '3rd-place-31' |
      '3rd-place' |
      '4th-place-25' |
      '4th-place' |
      '4th' |
      '4wd' |
      '5th-place-16' |
      '5th-place-26' |
      '5th-place' |
      'a-star-that-can-be-used-for-favorites-and-recommendations' |
      'add-toilet-1' |
      'anchor-4' |
      'anchor-7' |
      'anchor' |
      'aoi-family-crest' |
      'arrow-42' |
      'arrow-button-down-1' |
      'arrow-button-down-2' |
      'arrow-button-down-3' |
      'arrow-button-left-1' |
      'arrow-button-left-2' |
      'arrow-button-left-3' |
      'arrow-button-left-4' |
      'arrow-button-right-2' |
      'arrow-button-up-1' |
      'arrow-button-up-2' |
      'arrow-button-up-3' |
      'arrow-button-up-4' |
      'arrow-down-2' |
      'arrow-down-3' |
      'arrow-down-5' |
      'arrow-down-6' |
      'arrow-down-7' |
      'arrow-left-1' |
      'arrow-left-3' |
      'arrow-left-4' |
      'arrow-left-5' |
      'arrow-left-6' |
      'arrow-left-7' |
      'arrow-right-2' |
      'arrow-right-6' |
      'arrow-top-7' |
      'arrow-up-1' |
      'arrow-up-2' |
      'arrow-up-3' |
      'arrow-up-4' |
      'arrow-up-5' |
      'arrow-up-6' |
      'arrow' |
      'asterisk-symbol' |
      'at-sign' |
      'attention-mark-2' |
      'attention-mark-line-drawing' |
      'attention-mark' |
      'attention' |
      'autofocus-1' |
      'autofocus-2' |
      'backspace-delete' |
      'backspace' |
      'barcode' |
      'beginner-mark' |
      'bell-2' |
      'bell-5' |
      'bell-7' |
      'bell' |
      'big-crown' |
      'big-heart' |
      'blog-writing' |
      'blue-line' |
      'bluetooth-1' |
      'bluetooth-2' |
      'bluetooth-3' |
      'bonfire-2' |
      'bonfire-3' |
      'bonfire' |
      'book-7' |
      'book' |
      'bookmark-1' |
      'bookmark-2' |
      'bookmark-3' |
      'bookmark-4' |
      'bookmark-5' |
      'bookmark-6' |
      'brightness-2' |
      'brightness-57' |
      'brightness-8' |
      'brightness-setting' |
      'brightness' |
      'broken-heart-1' |
      'broken-link-1' |
      'broken-link-2' |
      'bug' |
      'canadian-flag' |
      'canadian-maple' |
      'caution-mark-13' |
      'caution-mark-6' |
      'caution-mark-7' |
      'caution-mark-8' |
      'caution-mark-9' |
      'caution-mark' |
      'celtic-cross-1' |
      'character-size-2' |
      'character-size-3' |
      'check-box' |
      'check-mark' |
      'checkbox' |
      'cherry-blossom-3' |
      'cherry-blossom-5' |
      'chrysanthemum-crest-2' |
      'cigarette' |
      'clapperboard-with-play-button-3' |
      'clapperboard-with-play-button' |
      'cloud-music-1' |
      'cloud-music-2' |
      'cloudy-weather-2' |
      'cloudy-weather' |
      'clover-mark-2' |
      'clover-mark-3' |
      'clover-mark-4' |
      'clover-mark-5' |
      'clover-mark' |
      'coin-locker-1' |
      'coin-locker-2' |
      'coin-locker-3' |
      'coin-locker-4' |
      'coin-locker-5' |
      'coin-locker-6' |
      'color-setting' |
      'comma-ish-glyph' |
      'control-button-12' |
      'control-button-14' |
      'control-button-36' |
      'control-button-39' |
      'control-button-45' |
      'control-button-48' |
      'control-button-50' |
      'control-button-53' |
      'control-button-56' |
      'control-button-6' |
      'control-button-63' |
      'control-button-77' |
      'control-button' |
      'cross-1' |
      'cross-2' |
      'cross-cursor-41' |
      'cross-cursor' |
      'crown-1' |
      'crown-15' |
      'crown-2' |
      'crown-24' |
      'crown-46' |
      'crown-5' |
      'crown-52' |
      'crown-65' |
      'crown-66' |
      'crown-9' |
      'crown' |
      'cute-heart-1' |
      'cute-heart-2' |
      'diamond-mark-2' |
      'diamond-mark-3' |
      'diamond-mark-5' |
      'diamond-mark' |
      'download-2' |
      'download-4' |
      'download-79' |
      'download-80' |
      'download-81' |
      'download-arrow' |
      'download' |
      'drone-prohibited-1' |
      'drop' |
      'eating-and-drinking-prohibited-2' |
      'egyptian-cross-1' |
      'egyptian-cross-2' |
      'eighth-note-4' |
      'eject-button-33' |
      'eject-button-47' |
      'eject-button-67' |
      'eject-button' |
      'electric' |
      'embed' |
      'empty-quote' |
      'exclamation-mark-21' |
      'exclamation-mark-23' |
      'exclamation-mark' |
      'eye-of-horus' |
      'face-recognition-1' |
      'face-recognition-2' |
      'facebook-like-2' |
      'falun-illustration-1' |
      'fashionable-peke' |
      'fast-forward-button-62' |
      'fast-forward-button-68' |
      'fast-forward-button' |
      'fat-reload' |
      'favorite-star-1' |
      'favorite-star-2' |
      'female-mark' |
      'festival-kanji' |
      'film-2' |
      'film-3' |
      'film-4' |
      'film' |
      'fingerprint-authentication-1' |
      'fingerprint-authentication-that-can-be-used-for' |
      'fingerprint' |
      'fireball-2' |
      'fireball-3' |
      'fireball-4' |
      'fireball' |
      'flame-2' |
      'flame-3' |
      'flame-illustration-1' |
      'flash-mark' |
      'fleur-de-lis-1' |
      'fleur-de-lis-2' |
      'font-size-1' |
      'footprint-1' |
      'footprint-2' |
      'free-bell-6' |
      'free-finger-and-arrow' |
      'free-image-image' |
      'free-like-hand' |
      'free-music-note-3' |
      'free-pictograms-of-s' |
      'free-settings-76' |
      'free-settings-gear' |
      'free-settings' |
      'free-weather-illustrations-5' |
      'free-with-a-crown-in-a-round-frame-part-2' |
      'full-screen-button-3' |
      'full-screen-button-4' |
      'full-screen-button-5' |
      'full-screen-button-6' |
      'full-screen-button-7' |
      'full-screen-display-button-1' |
      'function-1' |
      'function-2' |
      'function-3' |
      'gear-10' |
      'gear-11' |
      'gear-60' |
      'gear-64' |
      'gear-75' |
      'gear' |
      'gender-mark-1' |
      'gender-mark-2' |
      'glitter-5' |
      'glitter-decoration' |
      'glyph-outline' |
      'glyph' |
      'good-job-hand-2' |
      'good-job-hand' |
      'goodjob' |
      'gorgeous-crown' |
      'hand-gesture' |
      'hand-sign' |
      'hatena' |
      'heart-mark-2' |
      'heart-mark-3' |
      'heart-mark' |
      'heart-outline' |
      'hexagram-pictogram' |
      'hikiryomon-three-lines-in-a-circle-family-crest' |
      'hindu-symbol' |
      'hojo-ujiyasu-family-crest' |
      'hospital-map-mark' |
      'hot-spring-mark-1' |
      'hot-spring-mark' |
      'houndstooth-line-drawing' |
      'houndstooth-mark' |
      'house-30' |
      'house-54' |
      'house' |
      'html-tag' |
      'html5-logo' |
      'human-soul' |
      'i-put-a-ribbon-under-the-crown' |
      'ikari-3' |
      'ikari-that-can-be-used-for-part-5' |
      'ikari' |
      'illustration-of-a-pointing-hand' |
      'image-3' |
      'image-image-2' |
      'image' |
      'infinite-pictogram' |
      'infinity-symbol' |
      'information-3' |
      'information-4' |
      'information' |
      'install' |
      'iron-cross-1' |
      'iron-sign' |
      'islamic-1' |
      'key-closed-lock-2' |
      'key-closed-lock-3' |
      'layer' |
      'left-arrow' |
      'lightning-38' |
      'lightning-4' |
      'lightning-7' |
      'lightning' |
      'like-hand-3' |
      'like-hand' |
      'link-1' |
      'link-3' |
      'link-4' |
      'link-5' |
      'link-6' |
      'link' |
      'loading-1' |
      'loading-2' |
      'loading-3' |
      'login-door-1' |
      'login-door-2' |
      'magic-square-1' |
      'magic-square-2' |
      'magic-square-3' |
      'man-mark' |
      'mark-3-of-spades' |
      'mark-4-of-spades' |
      'mark-of-spades-2' |
      'medal' |
      'meloic-sign' |
      'menorah-1' |
      'menu-1' |
      'menu-11' |
      'menu-12' |
      'menu-13' |
      'menu-17' |
      'menu-18' |
      'menu-19' |
      'menu-2' |
      'menu-4' |
      'menu-5' |
      'menu-6' |
      'menu-7' |
      'menu-8' |
      'menu-9' |
      'microphone-2' |
      'microphone-3' |
      'microphone-5' |
      'microphone-element' |
      'minus' |
      'mori-motonari-family-crest' |
      'motion-picture-film' |
      'movie-film' |
      'movie-play-button-2' |
      'movie-play-button-78' |
      'movie-play-button' |
      'musical-note-2' |
      'musical-note' |
      'national-highway' |
      'nazi-ss-mark' |
      'nazi-symbol-1' |
      'nazi-symbol-2' |
      'nazi-symbol-3' |
      'night-sky' |
      'no-drone-mark-2' |
      'no-eating-or-drinking-1' |
      'no-parking-1' |
      'no-parking-2' |
      'no-parking' |
      'no-smoking' |
      'noren-of-hot-spring-inn' |
      'normal-thickness-cross-2' |
      'normal-thickness-x-3' |
      'not-good-1' |
      'not-good-2' |
      'not-good-3' |
      'nuclear-1' |
      'nuclear-mark-1' |
      'nuclear-mark-2' |
      'nuclear-mark-3' |
      'nuclear-power-plant-1' |
      'nuclear-power' |
      'oda-nobunaga-family-crest' |
      'ok' |
      'old-man-1' |
      'open-in-new-window-button-1' |
      'open-in-new-window-button-2' |
      'opened-lock-2' |
      'opened-lock-3' |
      'outlined-information' |
      'palm' |
      'pan-cursor-61' |
      'pan-cursor' |
      'parking-51' |
      'parking' |
      'paulownia-family-crest' |
      'pause-button-49' |
      'pause-button-69' |
      'pause-button' |
      'paw-1' |
      'paw-2' |
      'paw-3' |
      'pentagram-illustration' |
      'photo-4' |
      'photo-5' |
      'photo-6' |
      'photo-7' |
      'photo-8' |
      'photo-9' |
      'play-button' |
      'play-stop-button-17' |
      'play-stop-button' |
      'playing-card-clover-mark' |
      'plus-minus' |
      'plus' |
      'police-badge' |
      'police-mark-2' |
      'police-mark' |
      'pop-up' |
      'post-office-mark' |
      'pound-mark-1' |
      'pound-mark-2' |
      'pound-mark-3' |
      'pregnant-woman-1' |
      'prohibition-mark' |
      'pyramid-eye-1' |
      'pyramid-eye-2' |
      'pyramid-eye-3' |
      'pyramid-eye-illustration-4' |
      'question-mark-71' |
      'question-mark-outline' |
      'question-mark' |
      'quote-58' |
      'quote' |
      'radio-wave-status-1' |
      'radio-wave-status-2' |
      'reading' |
      'recycling-arrow-1' |
      'recycling-arrow-2' |
      'refresh-button' |
      'reload-10' |
      'reload-redo' |
      'reload' |
      'remove-link-button' |
      'repeat-button-1' |
      'repeat-button-2' |
      'reply-arrow-1' |
      'reply-arrow-2' |
      'reply-arrow-3' |
      'restroom-mark-1' |
      'restroom-mark-2' |
      'restroom-mark-4' |
      'retweet' |
      'rewind-button-40' |
      'rewind-button' |
      'ribbon-mark-1' |
      'ribbon-mark-2' |
      'right-arrow' |
      'romance-1' |
      'romance-2' |
      'rotation-lock-1' |
      'rotation-lock-2' |
      'rotation-lock-3' |
      'rotation-unlock' |
      'rupee-1-frame' |
      'rupee-2' |
      'sakura-4' |
      'sanada-yukimura-family-crest' |
      'seal-such-as-winning-part-2' |
      'seat-1' |
      'seat-belt' |
      'seat-pictogram-2' |
      'seo-1' |
      'seo-3' |
      'settings-gear-combination' |
      'settings-gear-part-2' |
      'settings' |
      'share-1' |
      'share-2' |
      'share-arrow-59' |
      'share-arrow' |
      'share' |
      'sharp-star' |
      'shooting-prohibited-2' |
      'shooting-prohibition-1' |
      'shooting-prohibition-3' |
      'shrink-button-2' |
      'shrink-button-3' |
      'shuffle-1' |
      'shuffle-2' |
      'shuffle-3' |
      'shutter-1' |
      'shutter-2' |
      'shutter-3' |
      'shutter-5' |
      'shutter-6' |
      'simple-crown-2' |
      'simple-crown' |
      'simple-good-hand' |
      'simple-like-hand-line-drawing' |
      'simple-like-hand' |
      'single-track-repeat-button-29' |
      'single-track-repeat-button' |
      'sitemap-1' |
      'sitemap-3' |
      'sleep-32' |
      'sleep' |
      'slide-button-1' |
      'slide-button-2' |
      'slide-button-4' |
      'snowman-10' |
      'snowman-4' |
      'snowman-6' |
      'snowman-7' |
      'snowman-8' |
      'snowman-9' |
      'snowman-illustration-5' |
      'snowman' |
      'soviet-union-symbol' |
      'space-saving-like-hand' |
      'spade-1' |
      'spanish-flag' |
      'speech-bubble-1' |
      'speech-bubble-10' |
      'speech-bubble-11' |
      'speech-bubble-12' |
      'speech-bubble-14' |
      'speech-bubble-15' |
      'speech-bubble-16' |
      'speech-bubble-17' |
      'speech-bubble-19' |
      'speech-bubble-20' |
      'speech-bubble-3' |
      'speech-bubble-4' |
      'speech-bubble-5' |
      'speech-bubble-6' |
      'speech-bubble-7' |
      'speech-bubble-8' |
      'speech-bubble-9' |
      'speech-bubble' |
      'square-heart-illustration-part-2' |
      'square-heart' |
      'stairs-10' |
      'stairs-12' |
      'stairs-2' |
      'stairs-3' |
      'stairs-6' |
      'stairs-7' |
      'stairs-8' |
      'stairs-9' |
      'stairs-pictogram-4' |
      'star-6' |
      'star-7' |
      'star-8' |
      'star-border' |
      'star-of-david-pictogram' |
      'stop-ban-palm' |
      'stop-palm' |
      'strong-wind-1' |
      'strong-wind-2' |
      'sun-2' |
      'sun-27' |
      'sun-28' |
      'sun-4' |
      'sun-5' |
      'sun-mark' |
      'sun' |
      'swirl-1' |
      'takeda-shingen-family-crest' |
      'target-1' |
      'target-2' |
      'target-3' |
      'target-4' |
      'target' |
      'thick-cross-2' |
      'thick-cross-3' |
      'thick-cross' |
      'thin-cross-2' |
      'thin-cross-3' |
      'thin-cross' |
      'this-finger-stop' |
      'three-point-leader-1' |
      'three-point-leader-2' |
      'three-way-family-crest' |
      'thumbs-up-hand' |
      'toilet-bowl-1' |
      'toilet-bowl-2' |
      'toilet-bowl-3' |
      'trash-can-22' |
      'trash-can-35' |
      'trash-can' |
      'trimming' |
      'twitter-2' |
      'twitter' |
      'typhoon-70' |
      'typhoon-73' |
      'typhoon-illustration' |
      'typhoon' |
      'u-turn-arrow-1' |
      'u-turn-arrow-2' |
      'uneven-crown' |
      'union-jack' |
      'up-arrow' |
      'upload-arrow' |
      'uv-1' |
      'uv-cut' |
      'very-well-done-1' |
      'video-play-button' |
      'video-playback-button-2' |
      'video-playback-mark-34' |
      'video-playback-mark-55' |
      'video-playback-mark' |
      'walking-smartphone-2' |
      'walking-smartphone-prohibition-mark' |
      'water-drop-1' |
      'water-drop-3' |
      'water-drop-4' |
      'wave-1' |
      'wave-2' |
      'weather-19' |
      'weather-2' |
      'weather-9' |
      'weather-rain-19' |
      'weather-rain' |
      'weather-snow-snowman' |
      'weather-sunny-and-cloudy' |
      'weather-symbol-1' |
      'weather-symbol-10' |
      'weather-symbol-12' |
      'weather-symbol-13' |
      'weather-symbol-15' |
      'weather-symbol-17' |
      'weather-symbol-18' |
      'weather-symbol-20' |
      'weather-symbol-22' |
      'weather-symbol-23' |
      'weather-symbol-3' |
      'weather-symbol-4' |
      'weather-symbol-6' |
      'weather-symbol-7' |
      'weather-symbol-8' |
      'well-mark' |
      'wheelchair-2' |
      'white-exclamation-mark-1' |
      'white-exclamation-mark-2' |
      'white-wi-fi' |
      'wi-fi-74' |
      'wi-fi-logo-mark' |
      'wi-fi' |
      'wifi-72' |
      'wifi' |
      'winner-cup-10' |
      'winner-cup-9' |
      'woman-mark' |
      'x' |
      'yin-yang-taiji-diagram' |
      'yoshihiro-shimazu-family-crest';

    type backgroundType = 'circle' | 'rect' | 'button';

    type positionType = 'top' | 'bottom' | 'right' | 'left' |
      'top_right' | 'top_left' | 'bottom_right' | 'bottom_left';

    type backgroundTypeObj = {
      type?: backgroundType;
      color?: string;
      radius?: number;
      borderRadius?: number;
    };

    type badgeTypeObj = {
      value?: number | string;
      fontSize?: string;
      position?: positionType;
      color?: string;
      backgroundColor?: string;
      radius?: number;
    };

    interface IconProps {
      name: iconNames;
      width?: number;
      height?: number;
      color?: string;
      stroke?: number;
      background?: backgroundType | backgroundTypeObj;
      badge?: number | string | badgeTypeObj;
    }

    const Icon: (props: IconProps) => ReactNode;

    export { iconNames };
    export default Icon;
}
